; ============================================================
;  PlatformIO Project Configuration
;  Board  : ESP32-WROOM-32U (ESP32 Dev Module)
;  Sensors: AHT20 (I2C 0x38) + MPU6050 (I2C 0x68)
; ============================================================

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	adafruit/Adafruit AHTX0 @ ^2.0.5
	bblanchon/ArduinoJson @ ^7.0.4


build_flags =
    -DCORE_DEBUG_LEVEL=0
    -std=gnu++17